/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2022-03-04 01:09:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.post;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("wanho:hasPermission", net.wanho.tag.PermissionFunction.class, "hasPermission", new Class[] {java.lang.String.class, java.util.List.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/mytag.tld", Long.valueOf(1626311834000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fwanho_005fpermission_0026_005fpermCondition;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fwanho_005fpermission_0026_005fpermCondition = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fwanho_005fpermission_0026_005fpermCondition.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/header.jsp", out, false);
      out.write("\r\n");
      out.write("<body class=\"gray-bg\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-div\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-12 select-info\">\r\n");
      out.write("\t\t\t\t<form id=\"condition-form\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"select-list gd\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>岗位编码：<input type=\"text\" name=\"postCode\" />\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>岗位名称：<input type=\"text\" name=\"postName\" />\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>岗位状态：<select name=\"status\" id=\"gw\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">所有</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"btn btn-primary btn-rounded btn-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"$.table.search($('form').attr('id'))\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-search\"></i>&nbsp;搜索</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-success btn-rounded btn-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"$.table.exportExcel($('form').attr('id'))\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-download\"></i>&nbsp;下载</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"btn-group hidden-xs\" id=\"toolbar\" role=\"group\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_wanho_005fpermission_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_wanho_005fpermission_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-12 select-info order-table\">\r\n");
      out.write("\t\t\t\t<table id=\"bootstrap-table\" data-mobile-responsive=\"true\"></table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/admin/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar editFlag = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wanho:hasPermission('admin:post:edit1',currentUser.menus)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\"\r\n");
      out.write("\t\tvar removeFlag =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wanho:hasPermission('admin:post:remove',currentUser.menus)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\"\r\n");
      out.write("\t\tvar prefix = ctx + \"admin/post\"\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : ctx\r\n");
      out.write("\t\t\t\t\t\t\t+ \"/DataServlet?method=dictData&dictType=sys_job_status\",\r\n");
      out.write("\t\t\t\t\tmethod : \"POST\",\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(res) {\r\n");
      out.write("\t\t\t\t\t\tif (res.success) {\r\n");
      out.write("\t\t\t\t\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t$(res.data)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfunction(i, item) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\thtml += '<option  value=\"'+item.dictValue+'\" name=\"action\">'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ item.dictLabel\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</option>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gw\").append(html);\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\talert(res.msg)\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tvar options = {\r\n");
      out.write("\t\t\t\turl : \"PostServlet?method=postList\",\r\n");
      out.write("\t\t\t\tcreateUrl : prefix + \"/add.jsp\",\r\n");
      out.write("\t\t\t\tupdateUrl : ctx + \"/PostServlet?method=to_postUpdate\",\r\n");
      out.write("\t\t\t\tremoveUrl : ctx + \"/PostServlet?method=postRemove\",\r\n");
      out.write("\t\t\t\tsortName : \"postSort\",\r\n");
      out.write("\t\t\t\tmodalName : \"岗位\",\r\n");
      out.write("\t\t\t\tsearch : false,\r\n");
      out.write("\t\t\t\tshowExport : false,\r\n");
      out.write("\t\t\t\tcolumns : [\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tcheckbox : true\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tfield : 'postId',\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '岗位编号'\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tfield : 'postCode',\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '岗位编码'\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tfield : 'postName',\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '岗位名称'\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tfield : 'postSort',\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '显示顺序'\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tfield : 'status',\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '状态',\r\n");
      out.write("\t\t\t\t\t\t\talign : 'center',\r\n");
      out.write("\t\t\t\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif (value == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn '<span class=\"badge badge-primary\">正常</span>';\r\n");
      out.write("\t\t\t\t\t\t\t\t} else if (value == 1) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn '<span class=\"badge badge-danger\">停用</span>';\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tfield : 'createTime',\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '创建时间',\r\n");
      out.write("\t\t\t\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\t\t\t\treturn new Date(row.createTime)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.toLocaleDateString();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '操作',\r\n");
      out.write("\t\t\t\t\t\t\talign : 'center',\r\n");
      out.write("\t\t\t\t\t\t\tformatter : function(value, row, index) {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar actions = [];\r\n");
      out.write("\t\t\t\t\t\t\t\tif(editFlag==\"true\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\tactions.push('<a class=\"btn btn-success btn-xs '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ editFlag\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ '\" href=\"javascript:voide(0)\" onclick=\"$.operate.edit(\\''\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ row.postId\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ '\\')\"><i class=\"fa fa-edit\"></i>编辑</a> ');\r\n");
      out.write("\t\t\t\t\t\t\t\tif(removeFlag==\"true\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\tactions.push('<a class=\"btn btn-danger btn-xs '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ removeFlag\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ '\" href=\"javascript:voide(0)\" onclick=\"$.operate.remove(\\''\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ row.postId\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ '\\')\"><i class=\"fa fa-remove\"></i>删除</a>');\r\n");
      out.write("\t\t\t\t\t\t\t\treturn actions.join('');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t} ]\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t$.table.init(options);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_wanho_005fpermission_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  wanho:permission
    net.wanho.tag.ButtonPermission _jspx_th_wanho_005fpermission_005f0 = (net.wanho.tag.ButtonPermission) _005fjspx_005ftagPool_005fwanho_005fpermission_0026_005fpermCondition.get(net.wanho.tag.ButtonPermission.class);
    boolean _jspx_th_wanho_005fpermission_005f0_reused = false;
    try {
      _jspx_th_wanho_005fpermission_005f0.setPageContext(_jspx_page_context);
      _jspx_th_wanho_005fpermission_005f0.setParent(null);
      // /admin/post/list.jsp(36,4) name = permCondition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_wanho_005fpermission_005f0.setPermCondition((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wanho:hasPermission('admin:post:add',currentUser.menus)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      int _jspx_eval_wanho_005fpermission_005f0 = _jspx_th_wanho_005fpermission_005f0.doStartTag();
      if (_jspx_eval_wanho_005fpermission_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<button class=\"btn btn-outline btn-success btn-rounded\" onclick=\"$.operate.add()\" shiro:hasPermission=\"system:post:add\">\r\n");
          out.write("\t                <i class=\"fa fa-plus\"></i> 新增\r\n");
          out.write("\t            </button>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_wanho_005fpermission_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_wanho_005fpermission_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fwanho_005fpermission_0026_005fpermCondition.reuse(_jspx_th_wanho_005fpermission_005f0);
      _jspx_th_wanho_005fpermission_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_wanho_005fpermission_005f0, _jsp_getInstanceManager(), _jspx_th_wanho_005fpermission_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_wanho_005fpermission_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  wanho:permission
    net.wanho.tag.ButtonPermission _jspx_th_wanho_005fpermission_005f1 = (net.wanho.tag.ButtonPermission) _005fjspx_005ftagPool_005fwanho_005fpermission_0026_005fpermCondition.get(net.wanho.tag.ButtonPermission.class);
    boolean _jspx_th_wanho_005fpermission_005f1_reused = false;
    try {
      _jspx_th_wanho_005fpermission_005f1.setPageContext(_jspx_page_context);
      _jspx_th_wanho_005fpermission_005f1.setParent(null);
      // /admin/post/list.jsp(42,4) name = permCondition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_wanho_005fpermission_005f1.setPermCondition((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wanho:hasPermission('admin:post:remove',currentUser.menus)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      int _jspx_eval_wanho_005fpermission_005f1 = _jspx_th_wanho_005fpermission_005f1.doStartTag();
      if (_jspx_eval_wanho_005fpermission_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<button class=\"btn btn-outline btn-danger btn-rounded\" onclick=\"$.operate.batRemove()\" shiro:hasPermission=\"system:post:remove\">\r\n");
          out.write("\t\t            <i class=\"fa fa-trash-o\"></i> 删除\r\n");
          out.write("\t\t        </button>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_wanho_005fpermission_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_wanho_005fpermission_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fwanho_005fpermission_0026_005fpermCondition.reuse(_jspx_th_wanho_005fpermission_005f1);
      _jspx_th_wanho_005fpermission_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_wanho_005fpermission_005f1, _jsp_getInstanceManager(), _jspx_th_wanho_005fpermission_005f1_reused);
    }
    return false;
  }
}
