/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2022-03-03 05:59:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class default_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<title>主页</title>\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\">\n");
      out.write("<link href=\"css/plugins/bootstrap/bootstrap.min.css?v=3.3.6\" rel=\"stylesheet\">\n");
      out.write("<link href=\"css/plugins/font-awesome/font-awesome.css?v=4.4.0\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<link href=\"css/plugins/animate/animate.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"css/style.css?v=4.1.0\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"gray-bg index\">\n");
      out.write("\n");
      out.write("\t<div class=\"wrapper wrapper-content\">\n");
      out.write("\n");
      out.write("\t\t<!--菜单首页：显示当前用户和当前时间开始 ========================================-->\n");
      out.write("\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-sm-12\">\n");
      out.write("\t\t\t\t<div class=\"alert alert-success\" id=\"nowTime\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--菜单首页：显示当前用户和当前时间结束 ========================================-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!--菜单首页：显示面板开始 ========================================-->\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-sm-4 \">\n");
      out.write("\t\t\t\t<div class=\"media\">\n");
      out.write("\t\t\t\t\t<div class=\"media-left\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary\" type=\"button\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-users fa-3x\"></i>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"media-right\">\n");
      out.write("\t\t\t\t\t\t用户总数: <br>3\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t\t<div class=\"media\">\n");
      out.write("\t\t\t\t\t<div class=\"media-left\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-danger\" type=\"button\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-life-ring fa-3x\"></i>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"media-right\">\n");
      out.write("\t\t\t\t\t\t外部图标: <br>34\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t\t<div class=\"media\">\n");
      out.write("\t\t\t\t\t<div class=\"media-left\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-warning\" type=\"button\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-clock-o fa-3x\" aria-hidden=\"true\"></i>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"media-right\">\n");
      out.write("\t\t\t\t\t\t<span class=\"loginTime\"></span> <cite>上次登录时间</cite>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--菜单首页：显示面板结束 ========================================-->\n");
      out.write("\n");
      out.write("\t\t<!--菜单首页:系统基本参数和最新文章的开始=================================-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-sm-12\">\n");
      out.write("\t\t\t\t<div class=\"panel panel-primary\">\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t<h3 class=\"panel-title\">\n");
      out.write("\t\t\t\t\t\t\t系统基本参数 <i class=\"fa fa-laptop\" aria-hidden=\"true\"></i>\n");
      out.write("\t\t\t\t\t\t</h3>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-striped table-bordered table-hover\">\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"150\">\n");
      out.write("\t\t\t\t\t\t\t\t<col>\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\n");
      out.write("\t\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>当前版本</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"version\">v2.0</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>开发作者</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"author\">驊驊龔頾</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>网站首页</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"homePage\">index.html</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>服务器环境</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"server\">windows</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>数据库版本</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"dataBase\">8.00.2039</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>最大上传限制</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"maxUpload\">2M</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>当前用户权限</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"userRights\">超级管理员</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-sm-12\">\n");
      out.write("\t\t\t\t<div class=\"panel panel-danger\">\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading \">\n");
      out.write("\t\t\t\t\t\t<h3 class=\"panel-title\">\n");
      out.write("\t\t\t\t\t\t\t最新文章 <i class=\"fa fa-fire fa-1x\" aria-hidden=\"true\"></i>\n");
      out.write("\t\t\t\t\t\t</h3>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-hover table-bordered table-striped\">\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\n");
      out.write("\t\t\t\t\t\t\t\t<col>\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"110\">\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\n");
      out.write("\t\t\t\t\t\t\t<tbody class=\"hot_news\">\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"javascript:;\"> css3用transition实现边框动画效果</a></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>2017-04-14</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"javascript:;\"> 自定义的模块名称可以包含/吗</a></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>2017-04-14</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"javascript:;\"> layui.tree如何ajax加载二级菜单</a></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>2017-04-14</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"javascript:;\"> layui.upload如何带参数？像jq的data:{}那样</a></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>2017-04-14</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"javascript:;\"> 表单元素长度应该怎么调整才美观</a></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>2017-04-14</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--菜单首页:系统基本参数和最新文章结束=================================-->\n");
      out.write("\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"ibox float-e-margins\">\n");
      out.write("\t\t\t\t\t<div class=\"ibox-title\">\n");
      out.write("\t\t\t\t\t\t<h5>二次开发</h5>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"ibox-content\">\n");
      out.write("\t\t\t\t\t\t<p>other.</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"ibox float-e-margins\">\n");
      out.write("\t\t\t\t\t<div class=\"ibox-title\">\n");
      out.write("\t\t\t\t\t\t<h5>联系信息</h5>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"ibox-content\">\n");
      out.write("\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-send-o\"></i> 博客：<a href=\"http://www.zi-han.net\" target=\"_blank\">http://www.wanho.net</a>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-qq\"></i> QQ：<a href=\"http://wpa.qq.com/msgrd?v=3&uin=516477188&site=qq&menu=yes\" target=\"_blank\">89115008</a>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-weixin\"></i> xx信：<a href=\"javascript:;\">89115008@</a>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-credit-card\"></i> xx宝：<a href=\"javascript:;\" class=\"支付宝信息\">89115008@qq.com</a>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t\t<div class=\"ibox float-e-margins\">\n");
      out.write("\t\t\t\t\t<div class=\"ibox-title\">\n");
      out.write("\t\t\t\t\t\t<h5>更新日志</h5>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"ibox-content no-padding\">\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-group\" id=\"version\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h5 class=\"panel-title\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a data-toggle=\"collapse\" data-parent=\"#version\" href=\"#v41\">v4.1.0</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<code class=\"pull-right\">2018.06.07</code>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</h5>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"v41\" class=\"panel-collapse collapse in\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"alert alert-warning\">此版本是一个维护版本，主要是升级和修复bug，让我们共同期待5.0版的到来</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t\t<div class=\"ibox float-e-margins\">\n");
      out.write("\t\t\t\t\t<div class=\"ibox-title\">\n");
      out.write("\t\t\t\t\t\t<h5>其它说明</h5>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"ibox-content\">other.</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- 全局js -->\n");
      out.write("\t<script src=\"js/plugins/jquery/jquery.min.js?v=2.1.4\"></script>\n");
      out.write("\t<script src=\"js/plugins/bootstrap/bootstrap.min.js?v=3.3.6\"></script>\n");
      out.write("\t<script src=\"js/plugins/layer/layer.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- 自定义js -->\n");
      out.write("\t<script src=\"js/index.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
